= Closing Thoughts
include::_attributes.adoc[]
:profile: 5g-ran-lab

In conclusion, deploying OpenShift for 5G RAN RDS deployments via GitOps using the ZTP workflow is a powerful and efficient way to manage infrastructure in large telco environments.

Through this lab, we have learned how the ZTP workflow helps us to deploy SNO clusters at scale by using OpenShift, RHACM, and Argo CD. All of this, while leveraging GitOps methodologies.

// In addition, we have learned how to integrate AAP automation with this workflow, adding automated imperative configuration when needed.

One topic that we didn't cover is the {cluster-compare-tool-link}[Cluster Compare Tool], with this tool you can verify that a cluster has been configured according to the {rds-link}[Reference Design Specification]. We encourage you to take a look and even run the tool against one of the SNOs you deployed in this lab.

We hope you enjoyed this lab, we are open to suggestions/feedback/contributions via pull requests.
