apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
resources:
  - 00_odf_config.yaml
  - 01_rhacm_config.yaml
  - 02_ai_config.yaml
  - 03_patch_provisioning.yaml
  - 04_mce_config.yaml
  - 05_ptp_config.yaml
  - 06_logging_config.yaml
